### ISSUE TITLE
Does Not Open

### ISSUE THREAD

**Issue by owenwinchell** [Inori/GPCS4#105]
When I Open The Exe It Crashes With A Blue Screen It Luckily Has Not Crashed My Pc Yet

**Comment by Inori** [comment]
GPCS4 is a user mode program, not likely to makek your computer bluescreen.

**Comment by Fox2Code** [comment]
@owenwinchell bluescreen are often caused by faulty drivers, please update your graphics drivers and Windows.
Also try to disable your antivirus to see if it's your antivirus causing the blue screen.

@Inori sadly user mode programs can bluescreen Windows, but when it's the case it's Windows fault, not the program fault.

**Comment by Inori** [comment]
@Fox2Code I mean, It is possible, but not likely.
